<!----SEGURIDAD----->
<?php
include_once'seguridaddirectivo.php';
?>
<?php
include_once'../all/head.php';
include_once'../all/header.php';
?>
<!-------CABECERA------>
<?php
include_once'../all/narvaradmin.php';
?>
<?php
include_once'../../controlador/directivoController/updateController.php';
?>
    <?php
include_once'../all/footer.php';
?>