<!----SEGURIDAD----->
<?php
include_once'seguridadsupervisor.php';
?>
<!---------CABECERA--------->
<?php
include_once'cabeceraSup.php';
?>
<!---------------CONTENEDORES---------------->
<?php
include_once'contenedorSup.php';
?>
<?php
include_once'../../controlador/supervisorController/verproyectosController.php';
?>
    <!--------------FIN CONTENEDORES---------------->
    <?php
include_once'finSup.php';
?>