<!----SEGURIDAD----->
<?php
include_once'seguridadaprendiz.php';
?>
<!---CABECERA---->
<?php
include_once'cabecera.aprendiz.php';
?>
<!---CONTENEDOR---->
<?php
include_once'contenedor.user.php';
?>
<!---CONTENEDOR PRINCIPAL---->
<?php
include_once'../../controlador/aprendizController/updateController.php';
?>
<!---FIN---->
<?php
include_once'fin.php';
?>
